name: APK Build and Comment
on: [push, workflow_dispatch]

# Add these permissions at the workflow level
permissions:
  contents: read        # Required for checkout
  issues: write        # Required for creating issue comments
  pull-requests: write # Required for PR comments (if needed)

jobs:
  build-and-comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Your existing build steps go here
      - name: Build APK (placeholder)
        run: |
          echo "Building APK..."
          # Your actual build commands
      
      # This is the step that was failing
      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: 1,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📱 APK Build Complete

| File | Size | Download |
|------|------|----------|
| Debug APK | 6276363 bytes | [Download](https://github.com/you112ef/77777/actions/runs/${context.runId}) |
| Release APK | 5050533 bytes | [Download](https://github.com/you112ef/77777/actions/runs/${context.runId}) |

**Build Info:**
- Commit: \`${context.sha}\`
- Build: #${context.runNumber}
- Date: ${new Date().toISOString()}

To test the APK:
1. Download from the Actions artifacts
2. Install on Android device
3. Test the sperm analysis functionality`
            });